config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  devise_for :users

  resources :users, only: [:show, :edit, :update] do 
    resource :avatar, only: [:create, :destroy]
  end

  resources :events do 
    resources :images, only: [:create, :destroy]
    resources :comments, only: [:create], module: :events
  end
  
  resources :comments do 
    resources :comments, only: [:create], module: :comments
  end

  resources :participations, only: [:index, :new, :create, :destroy]

  namespace :admin do
    root to: "events#index"
    resources :users
    resources :events do 
      put "unvalidate", on: :member
    end
    resources :comments
    resources :participations, except: [:index]
    resources :event_submissions, except: [:new] do 
      put "validate", on: :member
    end
  end

  get 'about', to: 'static_pages#about'
  get 'contact', to: 'static_pages#contact'
  get 'submission_success', to: 'events#submission_success'
  get 'thanks', to: 'participations#thanks', as: 'thanks'
end

app/models/participation.rb
class Participation < ApplicationRecord
  # Associations
  belongs_to :user
  belongs_to :event

  # Callbacks
  after_create :participation_email
  # Scopes
  scope :of_event, -> (event) { where(event: event) } 

  def participation_email
    ParticipationMailer.event_participation_email(self).deliver_now
  end
end

app/controllers/admin/participations_controller.rb
module Admin
  class ParticipationsController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/participations_controller.rb
class ParticipationsController < ApplicationController
  include EventsHelper
    before_action :authenticate_user!
    before_action :set_event, only: [:index, :new, :create, :thanks] # @event is another model, we load it in a traditional way using a before_action (required to be find with :event_id instead of :id)
    load_and_authorize_resource only: [:index, :destroy]
    # The 2 bellow require @event to be set first for the :new, :create & :thanks (wich is done in the before_action :set_event) 
    before_action :amount_to_be_charged, only: [:new, :create, :thanks]
    before_action :description, only: [:new, :create]
    
  def index    
    # https://github.com/CanCanCommunity/cancancan/wiki/Authorizing-controller-actions#load_resource
    @participations = @participations.of_event(@event) # @particiaptions loaded is a scope (scoped with the specified permissions). It's possible to scope on it with other conditions.
  end

  def new
    @participation = Participation.new(event: @event)
    authorize! :new, @participation
  end

  def create
    @participation = Participation.new(event: @event, user: current_user)
    authorize! :create, @participation # return here if authorization denied
    if @amount == 0 
      @participation.save(user: current_user, event: @event)
      flash[:success] = "Your are part of this event !"
      redirect_to thanks_path(event_id: @event.id)
    else
      begin
      #Best practice for stripe integration
      # https://rails.devcamp.com/trails/ruby-gem-walkthroughs/campsites/payment/guides/how-to-integrate-stripe-payments-in-a-rails-application-charges

      customer = StripeTool.create_customer(
                  email: params[:stripeEmail],
                  stripe_token: params[:stripeToken],
                 )

      charge = StripeTool.create_charge(
                customer_id: customer.id,
                amount: @amount,
                description: @description,
                currency: 'eur',
               )

      Participation.create(user: current_user, event: @event)

      redirect_to thanks_path(event_id: @event.id)

      rescue Stripe::CardError => e
        flash[:error] = e.message
        redirect_to @event
      end
    end
  end
  
  def destroy
    @participation.destroy
    flash[:info] = "You are no longer part of this event"
    redirect_back(fallback_location: root_path)
  end

  def thanks
  end
  
private

  def set_event
    @event = Event.find(params[:event_id])
  end

  
  def amount_to_be_charged
    # Amount in cents
    @amount = @event.price
  end
  
  def description
    @description = @event.title
  end
  
  # def ensure_current_user_is_not_already_particitpant 
  #   if current_user_already_participant?(@event)
  #     flash[:warning] = "You're already part of this event"
  #     redirect_to @event
  #   end
  # end
  
  # def ensure_current_user_is_administrator
  #   current_user_is_administrator?(@event)
  # end
end

app/helpers/participations_helper.rb
module ParticipationsHelper
  def current_user_participation(event)
    Participation.where(user:current_user, event:event).first
  end

  def participation_where(user, event)
    Participation.where(user: user, event: event).first
  end
end

app/views/participations/index.html.erb
<%= render partial: "shared/banner", locals: { title: "Dashboard" } %>

<div class="container">
  <div class="text-center">
    <h2>Participants registered for this event</h2>
  </div>

  <div class="list-group">
      <% @participations.each do |participation| %>
         <%= render partial: "users/user_card_list", locals: { user: participation.user, participation: participation } %>
      <% end %>
  </div>
  <div class="text-center">
    <%= link_to 'Edit this event', edit_event_path(@event), class:'btn btn-primary' %>
    <%= link_to 'Delete this event', event_path(@event), method: :delete, class: 'btn btn-danger' %>
  </div>
</div>

app/views/participations/new.html.erb
<div class="clear-absolute"></div>
<div class="container">
  <%= render partial: 'shared/error_messages', locals: {resource: @participation} %>

  <div class="text-center">
    <h2 class="text-center">Register for this Event !</h2>
  </div>
    <%= render partial: 'events/card_presentation_panel', locals: { event: @event, amount: @amount } %>
  <% if @event.is_free? %>
    <div class="text-center mt-3">
      <%= link_to 'Join Now', participations_path(event_id: @event.id), method: :post, class:'btn btn-lg btn-primary' %>
    </div>
  <% else %>
    <%= form_tag participations_path, method: :post, class:"text-center" do %>
      <%= hidden_field_tag "event_id", @event.id %>
      <article>
        <%# <label class="amount"> %>
          <%# <span><%= pretty_amount(@amount) %>
        <%# </label> %>
      </article>
      <script src="https://checkout.stripe.com/checkout.js"
              class="stripe-button"
              data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
              data-description="<%= @description %>"
              data-image="<%= url_for(@event.images.first)%>"
              <%# strip "talks" in cents %>
              data-amount="<%= @amount %>"
              data-label="Register Now"
              data-currency="eur"
              data-email="<%= current_user.email %>"
              data-locale="auto">
      </script>
    <% end %>
  <% end %>
</div>

app/views/participations/thanks.html.erb
<%= render partial: "shared/banner", locals: { title: "Thank You !" } %>

<div class="container">
  <h3 class="text-center">Successful Payment</h3>
  <% unless @event.is_free? %>
    <p>You paiment of <%= pretty_amount(@amount) %> has been accepted !</p>
  <% end %>
  <p>You are now part of the event: <%= @event.title %> ! You joined <%= @event.participants.count %> other participant(s)</p>
  <p>Go back to the event's page: <%= link_to @event.title, @event %></p>
  <p>Go back to Home page: <%= link_to 'Home', root_path %></p>
</div>