config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  devise_for :users

  resources :users, only: [:show, :edit, :update] do 
    resource :avatar, only: [:create, :destroy]
  end

  resources :events do 
    resources :images, only: [:create, :destroy]
    resources :comments, only: [:create], module: :events
  end
  
  resources :comments do 
    resources :comments, only: [:create], module: :comments
  end

  resources :participations, only: [:index, :new, :create, :destroy]

  namespace :admin do
    root to: "events#index"
    resources :users
    resources :events do 
      put "unvalidate", on: :member
    end
    resources :comments
    resources :participations, except: [:index]
    resources :event_submissions, except: [:new] do 
      put "validate", on: :member
    end
  end

  get 'about', to: 'static_pages#about'
  get 'contact', to: 'static_pages#contact'
  get 'submission_success', to: 'events#submission_success'
  get 'thanks', to: 'participations#thanks', as: 'thanks'
end

app/controllers/admin/event_submissions_controller.rb
module Admin
  class EventSubmissionsController < Admin::ApplicationController
    before_action :set_event, only: [:show, :edit, :update, :destroy, :validate]

    def index 
      # kaminari pagination
      @events = Event.where(validated: false).order("created_at ASC").page(params[:page]).per(20)
    end

    def show
    end

    def edit
    end

    def update
      if @event.update(event_params)
        flash[:success] = "Event successfully edited !"
        redirect_to edit_admin_event_submission_path(@event)
      else
        flash.now[:error] = "Event couldn't be edited"
        render :edit
      end
    end

    def destroy
      @event.destroy
      flash[:success] = "Event successfully deleted"
      redirect_to admin_event_submissions_path
    end

    def validate
      if @event.update(event_validate_params)
        flash[:success] = "Event successfully validated"
        redirect_to admin_event_submissions_path
      else
        flash[:success] = "Event counldn't be validated"
        redirect_to admin_event_submissions_path
      end
    end

  private 

    def set_event 
      @event = Event.find(params[:id])
    end

    def event_params 
      params.require(:event).permit(:title, :description, :location, :price, :start_date)
    end

    def event_validate_params 
      params.require(:event).permit(:validated)
    end

  end
end

app/views/admin/event_submissions/_form.html.erb
<%= form_for resource, url: url, html: { class: "form" } do |f| %>
  <%= render partial: 'components/error_messages', locals: {resource: resource} %>

  <div class="field-unit field-unit--required">
    <div class="field-unit__label">
      <%= f.label 'title' %>
    </div>
    <div class="field-unit__field">
      <%= f.text_field :title %>
    </div>
  </div>

  <div class="field-unit field-unit--optional">
    <div class="field-unit__label">
      <%= f.label 'start date' %>
    </div>
    <div class="field-unit__field">
      <%= f.text_field :start_date, :data => {:type => 'datetime' } %>
    </div>
  </div>

  <div class="field-unit field-unit--optional">
    <div class="field-unit__label">
      <%= f.label 'duration' %>
    </div>
    <div class="field-unit__field">
      <%= f.text_field :duration %>
    </div>
  </div>

  <div class="field-unit field-unit--optional">
    <div class="field-unit__label">
      <%= f.label 'description' %>
    </div>
    <div class="field-unit__field">
      <%= f.text_area :description %>
    </div>
  </div>

  <div class="field-unit field-unit--optional">
    <div class="field-unit__label">
      <%= f.label 'location' %>
    </div>
    <div class="field-unit__field">
      <%= f.text_field :location %>
    </div>
  </div>

  <div class="field-unit field-unit--optional">
    <div class="field-unit__label">
      <%= f.label 'price' %>
    </div>
    <div class="field-unit__field">
      <%= f.text_field :price %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/event_submissions/edit.html.erb
<header class="main-content__header" role="banner">
  <h1 class="main-content__page-title">
    Edit Event #<%= @event.id %>
  </h1>

  <div>
    <%= link_to "Show Event ##{@event.id}", admin_event_submission_path(@event.id),  class: "button" %>
  </div>
</header>

<section class="main-content__body">
  <%= render partial: 'admin/event_submissions/form', locals: { resource: @event, url: admin_event_submission_path(@event.id)  } %>
</section>

app/views/admin/event_submissions/index.html.erb
<header class="main-content__header" role="banner">
  <h1 class="main-content__page-title" id="page-title">
    Event Submissions
  </h1>
</header>

<section class="main-content__body main-content__body--flush">
  <table>
    <thead>
      <tr>
        <th class="cell-label" scope="col" role="columnheader">ID</th>
        <th class="cell-label" scope="col" role="columnheader">Title</th>
        <th class="cell-label" scope="col" role="columnheader">Administrator</th>
        <th class="cell-label" scope="col" role="columnheader">Created At</th>
      </tr>
    </thead>

    <tbody>
      <% @events.each do |event| %>
        <tr class="js-table-row" <%= %(tabindex=0 role=link data-url=#{admin_event_submission_path(event.id)}) %>>
            <td class="cell-data">
              <%= event.id %>
            </td>
            <td class="cell-data">
              <%= event.title %>
            </td>
            <td class="cell-data">
              User #<%= event.administrator.id %>
            </td>
            <td class="cell-data">
              <%= event.creation_date_and_time %>
            </td>
            <td>
              <%= link_to 'Edit', edit_admin_event_submission_path(event.id), class: "action-edit" %>
            </td>
            <td><%= link_to 'Destroy', admin_event_submission_path(event.id), method: :delete, data: { confirm: "Are you sure?" }, class: "text-color-red" %>
            </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= paginate @events %>
</section>

app/views/admin/event_submissions/show.html.erb
<header class="main-content__header" role="banner">
  <h1 class="main-content__page-title">
    Show Event #<%= @event.id %>
  </h1>

  <div>
    <%= link_to "Edit Event ##{@event.id}", edit_admin_event_submission_path(@event.id),  class: "button" %>
  </div>
</header>

<section class="main-content__body">
  <dl>
    <dt class="attribute-label" id="administrator">
      Administrator
    </dt>
    <dd class="attribute-data attribute-data--belongs-to">
      <%= link_to "User ##{@event.administrator.id}", admin_user_path(@event.administrator.id) %>
    </dd>
    <dt class="attribute-label" id="id">
      ID
    </dt>
    <dd class="attribute-data attribute-data">
      <%= @event.id %>
    </dd>
    <dt class="attribute-label" id="start-date">
      Start Date
    </dt>
    <dd class="attribute-data attribute-data">
      <%= @event.starting_date_time %>
    </dd>
    <dt class="attribute-label" id="duration">
      Duration
    </dt>
    <dd class="attribute-data attribute-data">
      <%= @event.duration %>
    </dd>
    <dt class="attribute-label" id="title">
      Title
    </dt>
    <dd class="attribute-data attribute-data">
      <%= @event.title %>
    </dd>
    <dt class="attribute-label" id="price">
      Price
    </dt>
    <dd class="attribute-data attribute-data">
      <%= @event.price %>
    </dd>
    <dt class="attribute-label" id="location">
      Location
    </dt>
    <dd class="attribute-data attribute-data">
      <%= @event.location %>
    </dd>
    <dt class="attribute-label" id="created_at">
      Created At
    </dt>
    <dd class="attribute-data attribute-data">
      <%= @event.created_at %>
    </dd>
    <dt class="attribute-label" id="updated_at">
      Updated At
    </dt>
    <dd class="attribute-data attribute-data">
      <%= @event.updated_at %>
    </dd>
  </dl>
    <%= form_for @event, url: validate_admin_event_submission_path(@event.id), method: :put, html: { class: "form" } do |f| %>
    <%= f.hidden_field :validated, value: true %>
      <div class="center">
        <%= submit_tag "Validate Event", data: { confirm: 'Validate Event?' }, class:'btn-validate-action '%>
      </div>
    <% end %>
</section>