config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  devise_for :users

  resources :users, only: [:show, :edit, :update] do 
    resource :avatar, only: [:create, :destroy]
  end

  resources :events do 
    resources :images, only: [:create, :destroy]
    resources :comments, only: [:create], module: :events
  end
  
  resources :comments do 
    resources :comments, only: [:create], module: :comments
  end

  resources :participations, only: [:index, :new, :create, :destroy]

  namespace :admin do
    root to: "events#index"
    resources :users
    resources :events do 
      put "unvalidate", on: :member
    end
    resources :comments
    resources :participations, except: [:index]
    resources :event_submissions, except: [:new] do 
      put "validate", on: :member
    end
  end

  get 'about', to: 'static_pages#about'
  get 'contact', to: 'static_pages#contact'
  get 'submission_success', to: 'events#submission_success'
  get 'thanks', to: 'participations#thanks', as: 'thanks'
end

app/models/event.rb
class Event < ApplicationRecord
  # virtual attributes to retrieve date and time in 2 different fields
  attr_accessor :starting_date, :starting_time
  
  # Associations
  has_many_attached :images
  belongs_to :administrator, class_name: "User"
  has_many :participations, dependent: :destroy
  has_many :participants, through: :participations, source: :user, dependent: :destroy
  has_many :comments, as: :commentable, dependent: :destroy
  # Validations
  validate :start_date_cannot_be_in_the_past
  validate :duration_must_be_positif_multiple_of_5
  validates :images,
    attached: true,
    allow_blank: true,
    content_type: ['image/png', 'image/jpg', 'image/jpeg'],
    limit: { min: 0, max: 3, message: 'Maximum 3 images allowed' }                                    
  validates_numericality_of :price,
    greater_than_or_equal_to:  0,
    less_than: 100000,
    only_integer: true,
    message: 'Price must be between 0 and 1000' 
  validates :duration, numericality: { only_integer: true }
  validates :title, presence: { message: "You must choose a title" }, length: { in: 5..140 }
  validates :description, presence: { message: "You must add a description" }, length: { in: 5..10_000 }
  validates :location, presence: { message: "You must choose a location" }
  # validates :starting_date, presence: { message: "You must choose a starting date" }
  # validates :starting_time, presence: { message: "You must choose a starting time" }

  # Scopes
  scope :validated, -> { where(validated: true) }
  scope :latest,-> (nb) { order(created_at: :desc).limit(nb) }

  def start_date_cannot_be_in_the_past
    errors.add(:start_date, "time and date must be present or can't be in the past") unless start_date.present? && DateTime.parse("#{start_date}") >= DateTime.now.change(offset: "+0000")
  end

  def duration_must_be_positif_multiple_of_5
    errors.add(:duration, "must be a multiple of 5 and at least 5 minutes") unless duration.present? && duration > 0 && duration % 5 == 0
  end

  # instance methods

  def starting_date_time
    self.start_date.strftime("%Y-%m-%d at %H:%M")
  end

  def ending_date_date_time
    end_date = self.start_date + self.duration.minutes
    end_date.strftime("%Y-%m-%d at %H:%M")
  end

  def is_free?
    self.price == 0
  end

  #return only the attachement objects associated with the events that or saved in db
  def event_images 
    images.select{ |img| img.persisted? }
  end
end

app/controllers/admin/events_controller.rb
module Admin
  class EventsController < Admin::ApplicationController

    # Overide index methode
    def scoped_resource
      resource_class.where(validated: true)
    end

    # request_resource = set_event
    def unvalidate
      if requested_resource.update(event_unvalidate_params)
        flash[:success] = "Event successfully Unvalidated"
        redirect_to admin_events_path
      else
        flash[:danger] = "Event couldn't be unvalidated"
        render admin_events_path
      end
    end

  private

    def event_unvalidate_params 
      params.require(:event).permit(:validated)
    end
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end
    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/events/comments_controller.rb
class Events::CommentsController < CommentsController
  before_action :set_commentable

private
  def set_commentable
    @commentable = Event.find(params[:event_id])
  end
end 

app/controllers/events_controller.rb
class EventsController < ApplicationController
  include EventsHelper
  before_action :authenticate_user!, except: [:index, :show]
  load_and_authorize_resource #load @event even for non restful action like :submission_success https://github.com/CanCanCommunity/cancancan/blob/develop/docs/Authorizing-controller-actions.md#choosing-actions
  before_action :amount_to_be_charged, only: [:show]
 
  # Cancancan take care of:
  # before_action :set_event, only: [:show, :edit, :update, :destroy]
  # before_action :ensure_current_user_is_administrator, only: [:edit, :update, :destroy]
  # before_action :ensure_event_is_validated, only: [:show]
  
  def index
    # Without cancancan, with a scope defined in event.rb model
    # @pagy, @events = pagy(Event.validated.with_attached_images.order("created_at DESC"), items: 9)
 
    # With cancancan, it's done already through the ability scope. The scoped events are loaded in @events
    @pagy, @events = pagy(@events.with_attached_images.order("created_at DESC"), items: 12)
  end
  
  def show
  end

  def new
  end

  def create
    @event.assign_attributes(administrator: current_user, start_date: parsed_datetime, duration: parsed_duration, price: formated_price)
    if @event.save 
      flash[:success] = "Your event has been created it will be reviewed & validated soon!"
      redirect_to submission_success_path(id: @event.id)
    else
      flash.now[:warning] = "Your event has not been created"
      render :new
    end
  end

  def edit
  end

  def update
    if @event.update(event_params)
      flash[:success] = "Event successfully edited !"
      redirect_to @event
    else
      flash.now[:warning] = "Event couldn't be edited"
      render :edit
    end
  end

  def destroy
    @event.destroy
    flash[:success] = "Event successfully deleted"
    redirect_to root_path
  end

  def submission_success
  end

private

  def event_params
    params.require(:event).permit(:title, :description, :location, :price, images: [])
  end  

  def parsed_datetime
    date = params.require(:event).permit(:starting_date)[:starting_date]
    time = params.require(:event).permit(:starting_time)[:starting_time]
    DateTime.parse("#{date} #{time}") if date.present? && time.present?
  end    

  def parsed_duration
    hours = params.require(:event).permit("duration(4i)")["duration(4i)"]
    minutes = params.require(:event).permit("duration(5i)")["duration(5i)"]
    minutes.to_i + hours.to_i * 60 
  end    

  def formated_price
    price = params.require(:event).permit(:price)[:price]
    price.to_i * 100
  end

  def amount_to_be_charged
    # Amount in cents
    @amount = @event.price
  end

# CanCanCan take car of:

# -Thanks to it's loading feature:

# def set_event
#   @event = Event.find(params[:id])
# end

# -Thanks to scoping to "administrator_id: user.id"

# def ensure_current_user_is_administrator
#   current_user_is_administrator?(@event)
# end

# -Thanks to scoping to "validated: true"

# def ensure_event_is_validated
#   unless @event.validated 
#     flash[:warning] = "This event is being reviewed for validation"
#     redirect_to root_path
#   end
# end
end

app/helpers/events_helper.rb
module EventsHelper
  # Not possible to have them instance variables cuz of current_user
  def current_user_already_participant?(event)
    event.participants.include?(current_user)
  end

  def current_user_is_administrator?(event)
    event.administrator == current_user
  end

  def display_status(event)
    event.validated ? 'Validated' : 'In process'
  end
end

app/views/events/_background_img_blur.html.erb
<% if @event.images.attached? %>
  <%= image_tag url_for(event.images.first), class: "event-bg-img" %>
<% else %>
  <%= image_tag "default-event-image", class: "event-bg-img" %>
<% end %>

app/views/events/_card_presentation_panel.html.erb
<div class="row card-presentation-panel">

    <div class="col-lg-5">
        <%= render partial: "events/carousel", locals: { event: event } %>
    </div>

    <div class="col-lg-7">
      <div class="text-center">
        <h3><%= event.title %></h3>
      </div>
      <div class="event-details">
        <p><b>N° of participants</b>: <%= event.participants.count %></p>
        <p><b>Organised by</b>: <%= event.administrator.username %></p>
        <p><b>Starting</b>: <%= event.starting_date_time %></p>
        <p><b>Ending</b>: <%= event.ending_date_date_time %></p>
        <p><b>Location</b>: <%= event.location %></p>
        <p><b>Price</b>: <%= pretty_amount(amount) %></p>
      </div>
    </div>
    
</div>

app/views/events/_carousel.html.erb
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <% event.images.each_with_index do |_, i| %>
      <li data-target="#carouselExampleIndicators" data-slide-to="<%= i %>" <%='class = active' if i == 0 %>></li>
    <%end%>
  </ol>
  <div class="carousel-inner" role="listbox">
    <% if event.images.attached? %>
      <% event.images.each_with_index do |img, i| %>
          <div class="carousel-item <%= 'active' if i == 0%>" style="background-image: url(<%= url_for(img.blob) %>)">
          </div>
      <% end %>
    <% else %>
      <div class="carousel-item active" style="background-image: url(<%= image_path('default-event-image.png') %>)">
      </div>
    <% end %>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/events/_event_card.html.erb
<div class="card card-presentation">
  <%= link_to event_path(event.id), class: "card-img-link" do %>
    <% display_event_images(event, "card-img").first %>
  <% end %>
  <div class="card-body">
    <% if local_assigns[:display_status] %>
      <%= render partial: 'events/event_status', locals: { event: event } %>
    <% end %>
    <p class="starting-date mb-2"><%= event.starting_date_time %></p>
    <p class="card-title">
      <%= link_to event.title, event_path(event.id) %>
    </p>
  </div>
</div>

app/views/events/_event_card_list.html.erb
<div class="row">
  <% events.each do |event| %>
  <div class="col-item col-xl-3 col-lg-4 col-sm-6">
    <% if local_assigns[:display_status] %>
      <%= render partial: "events/event_card", locals: {event: event, display_status: display_status } %>
    <% else %>
      <%= render partial: "events/event_card", locals: {event: event } %>
    <% end %>
  </div>
  <% end %>
</div>

app/views/events/_event_link_panel.html.erb
<% if current_user_is_administrator?(event) %>
<div class="row">
  <div class="col-12 d-flex event-link-panel">
    <%= link_to "Event Dashboard", participations_path(event_id: event.id), class: 'btn btn-lg btn-success' %><br />
  </div>
</div>
<% elsif current_user_already_participant?(event) %>
<div class="row">
  <div class="col-12 d-flex event-link-panel">
    <%= link_to "Cancel participation", participation_path(current_user_participation(event).id), method: :delete, class:'btn btn-lg btn-danger' %><br />
  </div>
</div>
<% else%>
<div class="row">
  <div class="col-12 d-flex event-link-panel">
    <%= link_to "Join the event !", new_participation_path(event_id: event.id), class: 'btn btn-lg btn-primary' %><br />
  </div>
</div>
<% end %>

app/views/events/_event_listing.html.erb
<div class="event-listing">
  <%= render partial: "card_presentation_panel", locals: { event: event, amount: amount } %>
  <%= render partial: "event_link_panel", locals: { event: event } %>

  <div class="event-description">
    <p class ="text-muted">Posted on <%= @event.creation_date_and_time %></p>
    <h3>About this event</h3>
    <p><%= event.description %></p>
  </div>
</div>

app/views/events/_event_status.html.erb
<% if event.validated? %>
  <p class="text-success"><%= display_status(event) %></p>
<% else%>
  <p class="text-danger"><%= display_status(event) %></p>
<% end %>

app/views/events/_form.html.erb
  <%= yield %>
<%= form_for resource, :html => { novalidate: true, class: "needs-validation" } do |f| %>

  <div class="form-group">
    <%= f.label 'title' %>
    <%= f.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label 'description' %>
    <%= f.text_area :description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label 'location' %>
    <%= f.text_field :location, class: "form-control" %>
  </div>

  <div class=" form-group">
    <%= f.label 'starting_date' %>
    <%= f.text_field :starting_date, class: "form-control", id: "datepicker" %>
  </div>

  <div class=" form-group">
    <%= f.label 'starting_time' %>
    <%= f.text_field :starting_time, class: "form-control", id: "timepicker" %>
  </div>

  <div class="form-group">
    <%= f.label 'duration' %>
    <%= f.time_select :duration, minute_step: 5, include_seconds: false, ignore_date: true, prompt: { hour: 'Hour', minute: 'Minute' }, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label 'price' %>
    <%= f.number_field :price, in: 0...1000, class: "form-control" %>
  </div>

  <% resource.event_images.each do |img| %>
    <%= image_tag img, size: 200  %>
    <%= link_to 'delete', event_image_path(resource, img), method: :delete, class:'btn btn-danger' %>
  <% end %>

  <div class="form-group">
    <%= f.label :images %><br>
    <%= f.file_field :images, multiple: true, accept: ".png,.jpeg,.jpg" %>
  </div>

  <%= submit_tag "Submit", class:"btn btn-primary" %>

<% end %>

app/views/events/edit.html.erb
<div class="container">
  <%= render layout: 'events/form', locals: { resource: @event } do %>
    <h2 class="text-center">Edit Event</h2>
  <% end %>
</div>

app/views/events/index.html.erb
<div class="clear-absolute"></div>
<div class="container">
<div class="text-center">
  <h2 class="my-4">Latest Events</h2>
</div>
  <%= render partial: "events/event_card_list", locals: {events: @events} %>

  <div class="text-center">
    <%== pagy_bootstrap_nav(@pagy) %>
  </div>
</div>

app/views/events/new.html.erb
<div class="clear-absolute"></div>
<div class="container">
  <%= render layout: 'events/form', locals: { resource: @event } do %>
  <div class="text-center">
    <h2>Organise an Event</h2>
  </div>
  <% end %>
</div>

app/views/events/show.html.erb
<div class="clear-absolute"></div>

<div class="container">
  <%= render partial: "event_listing", locals: { event: @event, amount: @amount } %>
  <%= render partial: "comments/comment_section", locals: { commentable: @event } %>
</div>

<div class="event-page-bg">
  <div class="img-wrapper">
    <%= render partial: "background_img_blur", locals: { event: @event } %>
  </div>
</div>

app/views/events/submission_success.html.erb
<div class="container">
  <h1 class="mt-5">Thank you for submitting an event !</h1>

  <p class="lead">It will be reviewed and validated very soon !</p>

  <%= link_to "See your event", event_path(@event.id) %> <br>
  <%= link_to "Home", root_path, class: "btn btn-primary"%>
</div>