config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  devise_for :users

  resources :users, only: [:show, :edit, :update] do 
    resource :avatar, only: [:create, :destroy]
  end

  resources :events do 
    resources :images, only: [:create, :destroy]
    resources :comments, only: [:create], module: :events
  end
  
  resources :comments do 
    resources :comments, only: [:create], module: :comments
  end

  resources :participations, only: [:index, :new, :create, :destroy]

  namespace :admin do
    root to: "events#index"
    resources :users
    resources :events do 
      put "unvalidate", on: :member
    end
    resources :comments
    resources :participations, except: [:index]
    resources :event_submissions, except: [:new] do 
      put "validate", on: :member
    end
  end

  get 'about', to: 'static_pages#about'
  get 'contact', to: 'static_pages#contact'
  get 'submission_success', to: 'events#submission_success'
  get 'thanks', to: 'participations#thanks', as: 'thanks'
end

app/controllers/admin/application_controller.rb
# All Administrate controllers inherit from this
# `Administrate::ApplicationController`, making it the ideal place to put
# authentication logic or other before_actions.
#
# If you want to add pagination or other controller-level concerns,
# you're free to overwrite the RESTful controller actions.
module Admin
  class ApplicationController < Administrate::ApplicationController
    before_action :authenticate_admin, :authenticate_user!

    def authenticate_admin
      redirect_to '/', alert: 'Not authorized.' unless current_user && access_whitelist
    end

  private

    def access_whitelist
      current_user.try(:admin?)
    end

    # Override this value to specify the number of elements to display at a time
    # on index pages. Defaults to 20.
    # def records_per_page
    #   params[:per_page] || 20
    # end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # For pagination
  include Pagy::Backend
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,
      keys: [:email, :username]) # authentication key is set to "login" and not "email" anymore, so we have to manually permit email
    devise_parameter_sanitizer.permit(:account_update,
      keys: [:first_name, :last_name, :description, :email])
  end

  rescue_from CanCan::AccessDenied do |exception|
    respond_to do |format|
      format.html { redirect_to main_app.root_url, alert: exception.message, status: :not_found }
      end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
  def bootstrap_class_for_flash(type)
    case type
      when 'info' then 'alert-info'
      when 'success' then 'alert-success'
      when 'danger' then 'alert-danger'
      when 'warning' then 'alert-warning'
      when 'error' then 'alert-danger' #override stripe's "error" flash to work with bootstrap
      when 'notice' then 'alert-success' #override devise's "notice" flash to work with bootstrap
      when 'alert' then 'alert-danger' #override devise's "alert" flash to work with bootstrap
    end
  end

  # Format price
  def pretty_amount(amount_in_cents)
    amount_in_cents == 0 ? 'Free' : number_to_currency(amount_in_cents.to_f / 100, locale: :fr)
  end


  # Event images
  def display_event_images(event, image_class= "")
    if event.images.attached?
      event.images.map { |img| image_tag img.blob, alt: 'default-event-image', class: image_class }
    else
      [image_tag('default-event-image.png', alt: 'default-event-image', class: image_class)]
    end
  end
end

app/views/application/_alert.html.erb
<% flash.to_hash.except('timedout').each do |type, msg| %>
  <div class="alert <%= bootstrap_class_for_flash(type) %> alert-dismissable fade show" role="alert">
    <%= msg %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
  </div>
<% end %>

app/views/application/_footer.html.erb
<footer class="footer">
  <div class="container">
    <div class="copyright">
      <small>Georges Atalla	&copy;2021</small>
    </div>
  </div>
</footer>

app/views/application/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark" id="main-nav">
    <div class="container">

      <!-- Brand button -->

      <a href="/" class="navbar-brand">
        Event<span class="highlight">Bright</span>
      </a>

      <!-- Navbar toggler button-->

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#nav-content" aria-controls="nav-content" aria-expanded="false" aria-label="Toggle navigation" style="border:none">
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- Navbar -->

      <div id="nav-content" class="collapse navbar-collapse">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
            <%= link_to 'Home', root_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Create event', new_event_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Contact', contact_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'About', about_path, class: 'nav-link' %>
          </li>
          <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Profile</a>
            <div class="dropdown-menu">
              <%= link_to 'Profile', user_path(current_user.id), class: 'dropdown-item' %>
              <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'dropdown-item' %>
              <div class="dropdown-divider"></div>
                <% if current_user.try(:admin?) %>
                  <%= link_to 'Admin dashboard', admin_root_path, class: 'dropdown-item' %>
                <% end %>
              </div>
            </div>
          </li>
          <% else %>
            <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Login/Signup
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to 'Login', user_session_path, class: 'dropdown-item' %>
              <%= link_to 'Signup', new_user_registration_path, class: 'dropdown-item' %>
            </div>
          </li>
          <% end %>
        </ul>
      </div>
    </div>
    <!-- Container -->
  </nav>
  <!-- Navigation -->
</header>